/**
 * Change Tracker Component
 * Displays diff visualization and commit message for lesson updates
 */

import { useState, useMemo } from 'react';
import {
  Box,
  Paper,
  Typography,
  TextField,
  Chip,
  Accordion,
  AccordionSummary,
  AccordionDetails,
  Alert,
} from '@mui/material';
import {
  ExpandMore,
  Add as AddIcon,
  Remove as RemoveIcon,
  Edit as EditIcon,
} from '@mui/icons-material';
import type { LessonDiff } from '../services/lessonDiffService';
import { generateCommitMessage, getDiffSummary } from '../services/lessonDiffService';

interface ChangeTrackerProps {
  diff: LessonDiff | null;
  commitMessage?: string;
  onCommitMessageChange?: (message: string) => void;
}

const ChangeTracker = ({ diff, commitMessage, onCommitMessageChange }: ChangeTrackerProps) => {
  const [customCommitMessage, setCustomCommitMessage] = useState('');

  // Auto-generate commit message from diff
  const autoGeneratedMessage = useMemo(() => {
    if (!diff) return '';
    return generateCommitMessage(diff);
  }, [diff]);

  // Get diff summary for display
  const summary = useMemo(() => {
    if (!diff) return null;
    return getDiffSummary(diff);
  }, [diff]);

  // Use custom message if provided, otherwise use auto-generated
  const effectiveCommitMessage = commitMessage ?? (customCommitMessage || autoGeneratedMessage);

  const handleCommitMessageChange = (newMessage: string) => {
    setCustomCommitMessage(newMessage);
    if (onCommitMessageChange) {
      onCommitMessageChange(newMessage);
    }
  };

  if (!diff) {
    return (
      <Paper sx={{ p: 3 }}>
        <Alert severity="info">No changes to display</Alert>
      </Paper>
    );
  }

  const renderFieldChange = (label: string, oldValue: any, newValue: any) => {
    const hasChange = JSON.stringify(oldValue) !== JSON.stringify(newValue);
    if (!hasChange) return null;

    return (
      <Box sx={{ mb: 2 }}>
        <Typography variant="subtitle2" gutterBottom>
          {label}
        </Typography>
        <Box
          sx={{
            bgcolor: 'error.50',
            p: 1,
            borderRadius: 1,
            mb: 0.5,
            fontFamily: 'monospace',
            fontSize: '0.875rem',
          }}
        >
          <RemoveIcon sx={{ fontSize: 16, verticalAlign: 'middle', mr: 0.5, color: 'error.main' }} />
          {String(oldValue)}
        </Box>
        <Box
          sx={{
            bgcolor: 'success.50',
            p: 1,
            borderRadius: 1,
            fontFamily: 'monospace',
            fontSize: '0.875rem',
          }}
        >
          <AddIcon sx={{ fontSize: 16, verticalAlign: 'middle', mr: 0.5, color: 'success.main' }} />
          {String(newValue)}
        </Box>
      </Box>
    );
  };

  const renderArrayChange = (
    label: string,
    added: string[],
    removed: string[],
    modified: Array<{ from: string; to: string }>
  ) => {
    if (added.length === 0 && removed.length === 0 && modified.length === 0) return null;

    return (
      <Accordion>
        <AccordionSummary expandIcon={<ExpandMore />}>
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
            <Typography variant="subtitle2">{label}</Typography>
            {added.length > 0 && <Chip label={`+${added.length}`} size="small" color="success" />}
            {removed.length > 0 && <Chip label={`-${removed.length}`} size="small" color="error" />}
            {modified.length > 0 && (
              <Chip label={`~${modified.length}`} size="small" color="warning" />
            )}
          </Box>
        </AccordionSummary>
        <AccordionDetails>
          <Box>
            {removed.length > 0 && (
              <Box sx={{ mb: 2 }}>
                <Typography variant="caption" color="error.main" gutterBottom>
                  Removed:
                </Typography>
                {removed.map((item, idx) => (
                  <Box
                    key={idx}
                    sx={{
                      bgcolor: 'error.50',
                      p: 1,
                      borderRadius: 1,
                      mb: 0.5,
                      fontFamily: 'monospace',
                      fontSize: '0.875rem',
                    }}
                  >
                    <RemoveIcon
                      sx={{ fontSize: 16, verticalAlign: 'middle', mr: 0.5, color: 'error.main' }}
                    />
                    {item}
                  </Box>
                ))}
              </Box>
            )}

            {added.length > 0 && (
              <Box sx={{ mb: 2 }}>
                <Typography variant="caption" color="success.main" gutterBottom>
                  Added:
                </Typography>
                {added.map((item, idx) => (
                  <Box
                    key={idx}
                    sx={{
                      bgcolor: 'success.50',
                      p: 1,
                      borderRadius: 1,
                      mb: 0.5,
                      fontFamily: 'monospace',
                      fontSize: '0.875rem',
                    }}
                  >
                    <AddIcon
                      sx={{ fontSize: 16, verticalAlign: 'middle', mr: 0.5, color: 'success.main' }}
                    />
                    {item}
                  </Box>
                ))}
              </Box>
            )}

            {modified.length > 0 && (
              <Box>
                <Typography variant="caption" color="warning.main" gutterBottom>
                  Modified:
                </Typography>
                {modified.map((item, idx) => (
                  <Box key={idx} sx={{ mb: 1 }}>
                    <Box
                      sx={{
                        bgcolor: 'error.50',
                        p: 1,
                        borderRadius: 1,
                        mb: 0.5,
                        fontFamily: 'monospace',
                        fontSize: '0.875rem',
                      }}
                    >
                      <RemoveIcon
                        sx={{ fontSize: 16, verticalAlign: 'middle', mr: 0.5, color: 'error.main' }}
                      />
                      {item.from}
                    </Box>
                    <Box
                      sx={{
                        bgcolor: 'success.50',
                        p: 1,
                        borderRadius: 1,
                        fontFamily: 'monospace',
                        fontSize: '0.875rem',
                      }}
                    >
                      <AddIcon
                        sx={{
                          fontSize: 16,
                          verticalAlign: 'middle',
                          mr: 0.5,
                          color: 'success.main',
                        }}
                      />
                      {item.to}
                    </Box>
                  </Box>
                ))}
              </Box>
            )}
          </Box>
        </AccordionDetails>
      </Accordion>
    );
  };

  return (
    <Paper sx={{ p: 3 }}>
      <Typography variant="h6" gutterBottom>
        <EditIcon sx={{ verticalAlign: 'middle', mr: 1 }} />
        Changes Summary
      </Typography>

      {/* Change Statistics */}
      {summary && (
        <Box sx={{ mb: 3 }}>
          <Chip label={summary} size="small" variant="outlined" />
        </Box>
      )}

      {/* Commit Message */}
      <Box sx={{ mb: 3 }}>
        <TextField
          fullWidth
          multiline
          rows={3}
          label="Commit Message"
          value={effectiveCommitMessage}
          onChange={(e) => handleCommitMessageChange(e.target.value)}
          helperText="Auto-generated from changes. You can customize it."
          variant="outlined"
        />
      </Box>

      {/* Field Changes */}
      {diff.fieldsChanged.length > 0 && (
        <Box sx={{ mb: 3 }}>
          <Typography variant="subtitle1" gutterBottom>
            Fields Modified
          </Typography>
          <Box sx={{ display: 'flex', gap: 1, flexWrap: 'wrap' }}>
            {diff.fieldsChanged.map((field) => (
              <Chip key={field} label={field} size="small" color="primary" variant="outlined" />
            ))}
          </Box>
        </Box>
      )}

      {/* Content Diff */}
      {diff.contentDiff && (
        <Box sx={{ mb: 3 }}>
          <Accordion>
            <AccordionSummary expandIcon={<ExpandMore />}>
              <Typography variant="subtitle1">Content Changes</Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Box
                component="pre"
                sx={{
                  fontFamily: 'monospace',
                  fontSize: '0.875rem',
                  whiteSpace: 'pre-wrap',
                  wordBreak: 'break-word',
                  bgcolor: 'grey.50',
                  p: 2,
                  borderRadius: 1,
                  maxHeight: '400px',
                  overflow: 'auto',
                }}
              >
                {diff.contentDiff}
              </Box>
            </AccordionDetails>
          </Accordion>
        </Box>
      )}

      {/* Metadata Changes */}
      {Object.keys(diff.metadataDiff).length > 0 && (
        <Box sx={{ mb: 3 }}>
          <Typography variant="subtitle1" gutterBottom>
            Metadata Changes
          </Typography>
          {Object.entries(diff.metadataDiff).map(([key, value]) => {
            if (key === 'tags' && Array.isArray(value.old) && Array.isArray(value.new)) {
              const added = value.new.filter((t: string) => !value.old.includes(t));
              const removed = value.old.filter((t: string) => !value.new.includes(t));
              return renderArrayChange('Tags', added, removed, []);
            }
            return renderFieldChange(key, value.old, value.new);
          })}
        </Box>
      )}

      {/* Vocabulary Changes */}
      {(diff.vocabularyAdded.length > 0 ||
        diff.vocabularyRemoved.length > 0 ||
        diff.vocabularyModified.length > 0) && (
        <Box>
          <Typography variant="subtitle1" gutterBottom>
            Vocabulary Changes
          </Typography>
          {renderArrayChange(
            'Vocabulary Entries',
            diff.vocabularyAdded.map((v) => `${v.word}: ${v.definition}`),
            diff.vocabularyRemoved.map((v) => `${v.word}: ${v.definition}`),
            diff.vocabularyModified.map((v) => ({
              from: `${v.word}: ${v.oldDefinition}`,
              to: `${v.word}: ${v.newDefinition}`,
            }))
          )}
        </Box>
      )}
    </Paper>
  );
};

export default ChangeTracker;
